# Communication parameters
common: &common
  noise_type: 'AWGN' # AWGN, Rayleigh, Rician
  k_ratio: 0 # For Rayleigh channel
  snr_db: 10
tradicom:
  n_ldpc: 6144
  k_ldpc: 2048
  num_bits_per_symbol: 6
  demapping_method: 'app'
  ldpc_cn_type: 'boxplus'
  <<: *common
jscc:
  zdim: 4096
  power: 1 # null 
  <<: *common


  
